### ISSUE TITLE
Meeting errors that `element 0 of tensors does not require grad and does not have a grad_fn`

### ISSUE THREAD

**Issue by lemon-awa** [Sadcardation/MLLM-Refusal#1]
The errors you’re encountering when running the `attack_benchmark_normal_random` method are related to issues with gradient tracking in PyTorch.
When I try to running case1 in the attack.sh, using model LLAVA and dataset VQAv2, I meet errors when code went to `grad = torch.autograd.grad(group_loss, pert_tensor_denormal)[0]` in the `models/LLaVA/utils/visual_attacker.py`,  the errors is that
`  File "MLLM-Refusal/models/LLaVA/utils/visual_attacker.py", line 65, in attack_method
    return self.attack_benchmark_normal_random(inputs, num_iter, lr)
  File "MLLM-Refusal/models/LLaVA/utils/visual_attacker.py", line 117, in attack_benchmark_normal_random
    grad = torch.autograd.grad(group_loss, pert_tensor_denormal)[0]
  File ".conda/envs/mllm_refusal/lib/python3.10/site-packages/torch/autograd/__init__.py", line 394, in grad
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`
 
And I have tried to comment the command that `self.model.requires_grad_(False)`, but I met new errors that
`  File "=MLLM-Refusal/models/LLaVA/utils/visual_attacker.py", line 65, in attack_method
    return self.attack_benchmark_normal_random(inputs, num_iter, lr)
  File "MLLM-Refusal/models/LLaVA/utils/visual_attacker.py", line 121, in attack_benchmark_normal_random
    grad = torch.autograd.grad(group_loss, pert_tensor_denormal)[0]
  File ".conda/envs/mllm_refusal/lib/python3.10/site-packages/torch/autograd/__init__.py", line 394, in grad
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.`

**Comment by Sadcardation** [comment]
Thanks for your issue! It seems that I forget to mention we should also comment `@torch.no_grad()` in image encoder of LLaVA, otherwise the gradient would not be passed correctly. The modeling file of clip encoder for LLaVA is at llava/model/multimodal_encoder/clip_encoder.py
